mercure:
    hubs:
        default:
            url: 'http://caddy/.well-known/mercure'
            public_url: 'https://%env(HOST)%/.well-known/mercure'
            jwt:
                secret: '%env(APP_SECRET)%'
                publish: '*'
