services:
  php:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-latest}
    environment:
      APP_SECRET: ${APP_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      TZ: ${TZ:-UTC}

  caddy:
    image: ${DOCKER_REGISTRY}-caddy:${DOCKER_TAG:-latest}
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
