services:
  php:
    build:
      context: .
      target: symfony_php_dev
      args:
        TZ: ${TZ:-UTC}
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      TZ: ${TZ:-UTC}
    extra_hosts:
      - host.docker.internal:host-gateway

  caddy:
    build:
      context: .
      target: app_caddy
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "80:80"
    volumes:
      - ./public:/srv/app/public:ro
  redis:
    ports:
      - "6379:6379"
  database:
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8001:8025"
