version: "3.4"

services:
  php:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-main}
    volumes:
      - uploads:/srv/app
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  caddy:
    image: ${DOCKER_REGISTRY}-caddy/php:${DOCKER_TAG:-main}
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
  workers:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-main}
    deploy:
      mode: replicated
      replicas: 3
  cron:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-main}

volumes:
  uploads:
