services:
  php:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-latest}
    volumes:
      - uploads:/srv/app/public/uploads
      - ./.env:/srv/app/.env.local
    environment:
      APP_SECRET: ${APP_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      TZ: ${TZ:-UTC}

  caddy:
    image: ${DOCKER_REGISTRY}-caddy:${DOCKER_TAG:-latest}
    volumes:
      - uploads:/srv/app/public/uploads
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DOCKER_REGISTRY}-caddy.rule=Host(`${HOST:-localhost}`)"
      - "traefik.http.routers.${DOCKER_REGISTRY}-caddy.entrypoints=websecure"
      - "traefik.http.routers.${DOCKER_REGISTRY}-caddy.tls.certresolver=myresolver"
      - "traefik.http.services.${DOCKER_REGISTRY}-caddy.loadbalancer.server.port=80"

volumes:
  uploads:
