version: "3.4"

services:
  php:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-latest}
    volumes:
      - uploads:/srv/app/public/uploads
      - ./.env:/srv/app/.env.local
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  caddy:
    image: ${DOCKER_REGISTRY}-caddy:${DOCKER_TAG:-latest}
    volumes:
      - uploads:/srv/app/public/uploads
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
  workers:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-latest}
    deploy:
      mode: replicated
      replicas: 3
  cron:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-latest}

volumes:
  uploads:
