services:
  php:
    image: ${DOCKER_REGISTRY}-php:${DOCKER_TAG:-latest}
    networks:
      - traefik
    volumes:
      - ./uploads:/srv/app/public/uploads
      - ./.env:/srv/app/.env.local
    environment:
      APP_SECRET: ${APP_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      TZ: ${TZ:-UTC}

  caddy:
    image: ${DOCKER_REGISTRY}-caddy:${DOCKER_TAG:-latest}
    networks:
      - traefik
    volumes:
      - ./uploads:/srv/app/public/uploads
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${HOST:-localhost}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
  database:
    networks:
      - traefik
  redis:
    networks:
      - traefik

volumes:
  uploads:

networks:
  traefik:
    external: true
