services:
  php:
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      test: '/usr/local/bin/docker-healthcheck'
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - default

  caddy:
    depends_on:
      - php
    networks:
      - default
    environment:
      SERVER_NAME: ${HOST:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      TZ: ${TZ:-UTC}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    restart: unless-stopped
    networks:
      - default
    environment:
      TZ: ${TZ:-UTC}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - redis_data:/data:rw
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
volumes:
  php_socket:
  db_data:
  caddy_data:
  caddy_config:
  redis_data:

networks:
    default:
        external:
          name: traefik
