version: "3.4"

services:
  php:
    volumes:
      - uploads:/srv/app
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  caddy:
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
  workers:
    deploy:
      mode: replicated
      replicas: 3

volumes:
  uploads:
