version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
  workers:
    build:
      context: .
      target: symfony_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    extra_hosts:
      - host.docker.internal:host-gateway
  cron:
    build:
      context: .
      target: symfony_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - ./crontab.conf:/etc/cron.d/root:ro
    extra_hosts:
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
  database:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"

  node:
    build:
      context: .
      target: symfony_node
    volumes:
      - ./:/srv/app
    command: 'yarn encore dev --watch'
