name: Build

on:
    push:
    pull_request:

jobs:
    build:
        name: Docker build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: docker/setup-buildx-action@v1
            - name: Log in to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                registry: ${{ secrets.DOCKER_HOST }}
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta_php
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: ${{ secrets.DOCKER_REGISTRY }}-php
            - name: Build and push Docker image (php)
              uses: docker/build-push-action@v3.2.0
              with:
                context: .
                target: symfony_php
                cache-from: type=gha
                cache-to: type=gha,mode=max
                push: true
                tags: ${{ steps.meta_php.outputs.tags }}
                labels: ${{ steps.meta_php.outputs.labels }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta_caddy
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: ${{ secrets.DOCKER_REGISTRY }}-caddy
            - name: Build and push Docker image (caddy)
              uses: docker/build-push-action@v3.2.0
              with:
                context: .
                target: app_caddy
                push: true
                cache-from: type=gha
                cache-to: type=gha,mode=max
                tags: ${{ steps.meta_caddy.outputs.tags }}
                labels: ${{ steps.meta_caddy.outputs.labels }}
    test:
        name: Docker test
        runs-on: ubuntu-latest
        needs: build
        steps:
          - uses: actions/checkout@v3
          - name: Log in to Docker Hub
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
              registry: ${{ secrets.DOCKER_HOST }}
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - uses: isbang/compose-action@v1.4.1
            with:
              compose-file: |
                docker-compose.yml
                docker-compose.prod.yml
              env:
                DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
              down-flags: "--volumes"
              services: |
                caddy
                php
          - name: Run tests
            run: |
              docker-compose exec php composer test
