name: CI

on:
    push:
    pull_request:

jobs:
    build:
        name: Docker build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: docker/build-push-action@v3.2.0
              with:
                context: .
                cache-from: type=gha
                cache-to: type=gha,mode=max
                target: symfony_php
                tags: test-image:latest
                push: false
            - uses: addnab/docker-run-action@v3
              with:
                image: test-image:latest
                run: /usr/bin/composer test
            - name: Log in to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta_php
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: ${{ secrets.DOCKER_REGISTRY }}-php
            - name: Build and push Docker image (php)
              uses: docker/build-push-action@v3.2.0
              with:
                context: .
                target: symfony_php
                cache-from: type=gha
                cache-to: type=gha,mode=max
                push: true
                tags: ${{ steps.meta_php.outputs.tags }}
                labels: ${{ steps.meta_php.outputs.labels }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta_caddy
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: ${{ secrets.DOCKER_REGISTRY }}-caddy
            - name: Build and push Docker image (caddy)
              uses: docker/build-push-action@v3.2.0
              with:
                context: .
                target: app_caddy
                push: true
                cache-from: type=gha
                cache-to: type=gha,mode=max
                tags: ${{ steps.meta_caddy.outputs.tags }}
                labels: ${{ steps.meta_caddy.outputs.labels }}
