name: Deploy Prod

on:
  push:
    branches: ["main"]
#  workflow_run:
#    workflows: ["Build"]
#    types:
#      - completed

env:
  REGISTRY: ${{ secrets.REGISTRY || 'ghcr.io' }}
  FOLDER: /var/www/prod
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME || github.actor }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}
  DOCKER_TAG: ${{ github.ref_name }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  ENV_FILE: ${{ vars.ENV_FILE || '' }}
  DEPLOY: true
  TZ: UTC
  APP_NAME: prod

jobs:
  deploy:
    name: Install docker and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Downcase REPO
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME@L}" >> ${GITHUB_ENV}
      - uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          source: "docker-compose.yml,docker-compose.prod.yml,docker-compose.traefik.yml,docker/docker.sh, docker/deploy.sh"
          target: ${{ env.FOLDER }}
      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v1.1.0
        env:
          ENV_FILE: ${{ env.ENV_FILE }}
          PROJECT_FOLDER: ${{ env.FOLDER }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}
          APP_NAME: ${{ env.APP_NAME }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          debug: true
          envs: ENV_FILE,REGISTRY,IMAGE_NAME,DOCKER_TAG,DOCKER_USERNAME,DOCKER_PASSWORD,PROJECT_FOLDER,APP_NAME
          script: |
            cd ${{ env.FOLDER }}/docker
            export ENV_FILE=$ENV_FILE
            export PROJECT_FOLDER=$PROJECT_FOLDER
            export REGISTRY=$REGISTRY
            export IMAGE_NAME=$IMAGE_NAME
            export DOCKER_TAG=$DOCKER_TAG
            export DOCKER_USERNAME=$DOCKER_USERNAME
            export DOCKER_PASSWORD=$DOCKER_PASSWORD
            export APP_NAME=$APP_NAME
            chmod +x ./deploy.sh
            ./deploy.sh
