name: Deploy

on:
  create:
    tags:
      - v*
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Install docker and deploy
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "docker-compose.yml,docker-compose.prod.yml"
          target: "/var/www"
      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        env:
          ENV_FILE: ${{ vars.ENV_FILE }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: ENV_FILE,DOCKER_REGISTRY
          script: |
            if [[ $(which docker) == "" ]]; then
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              apt-cache policy docker-ce
              sudo apt-get install -y docker-ce
              sudo apt-get install -y docker-compose
            fi
            echo "${{ vars.ENV_FILE }}" > /var/www/.env
            mv /var/www/docker-compose.prod.yml /var/www/docker-compose.override.yml
            echo "DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}" >> /var/www/.env
            echo "${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_HOST }} --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            cd /var/www && docker-compose pull && docker-compose up -d 
            sudo docker image prune -f
