name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  FOLDER: /var/www

jobs:
  deploy:
    name: Install docker and deploy
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: downcase REPO
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME@L}" >> ${GITHUB_ENV}
      - uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "docker-compose.yml,docker-compose.prod.yml,docker/docker.sh"
          target: ${{ env.FOLDER }}
      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        env:
          ENV_FILE: ${{ vars.ENV_FILE }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: ENV_FILE,REGISTRY,IMAGE_NAME
          script: |
            cd ${{ env.FOLDER }}
            chmod +x ./docker.sh
            ./docker.sh
            echo "${{ vars.ENV_FILE }}" > .env
            mv docker-compose.prod.yml docker-compose.override.yml
            echo "DOCKER_REGISTRY=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> .env
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ env.REGISTRY }} --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker compose pull && docker compose up -d 
            sudo docker image prune -f
